# Generated by Django 5.2.16 on 2026-07-14 01:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nomina', models.CharField(help_text='Identificador alfanumérico único del usuario.', max_length=20, unique=True, verbose_name='ID / número de nómina')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('cantidad_videos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de videos a subir')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del video')),
                ('extension', models.CharField(choices=[('mp4', 'MP4'), ('avi', 'AVI'), ('mov', 'MOV'), ('mkv', 'MKV'), ('wmv', 'WMV'), ('flv', 'FLV'), ('webm', 'WEBM')], max_length=10, verbose_name='Extensión')),
                ('tamano_mb', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(3.0)], verbose_name='Tamaño (MB)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos_app.personamodel', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['id'],
            },
        ),
    ]
