# Generated by Django 5.2.16 on 2026-07-14 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='archivo',
            field=models.FileField(default='', upload_to='videos/%Y/%m/%d/', verbose_name='Archivo de video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='extension',
            field=models.CharField(choices=[('mp4', 'MP4'), ('avi', 'AVI'), ('mov', 'MOV'), ('mkv', 'MKV'), ('wmv', 'WMV'), ('flv', 'FLV'), ('webm', 'WEBM')], help_text='Se detecta automáticamente a partir del archivo subido.', max_length=10, verbose_name='Extensión'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='tamano_mb',
            field=models.DecimalField(decimal_places=2, help_text='Se calcula automáticamente a partir del archivo subido.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(3.0)], verbose_name='Tamaño (MB)'),
        ),
    ]
