# Generated by Django 5.2.16 on 2026-07-14 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_videomodel_archivo_alter_videomodel_extension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta (usuario/contraseña) con la que esta persona inicia sesión.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
    ]
